name: Build and Publish Azure Functions

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: build and package Azure Functions
      run: |
        dotnet restore
        dotnet build -c Release
        #dotnet test
        dotnet publish -c Release -o dist
      
    - name: Publish to Azure Functions
      uses: Azure/functions-action@v1.4.0
      with:
        app-name: poke-function
        package: dist
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
